# Generated by Django 5.2 on 2025-04-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cognome', models.CharField(blank=True, help_text='Per persone fisiche', max_length=150, null=True, verbose_name='Nome/Cognome')),
                ('ragione_sociale', models.CharField(blank=True, help_text='Per aziende', max_length=200, null=True, verbose_name='Ragione Sociale')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('indirizzo', models.TextField(blank=True, null=True, verbose_name='Indirizzo')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Altre Informazioni Rilevanti')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
                'ordering': ['ragione_sociale', 'nome_cognome'],
            },
        ),
        migrations.CreateModel(
            name='SpazioPubblicitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificativo', models.CharField(help_text='Es. BS-001, MI-P05', max_length=50, unique=True, verbose_name='Identificativo Univoco')),
                ('descrizione', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrizione Breve')),
                ('posizione_indirizzo', models.TextField(help_text='Indirizzo completo dello spazio', verbose_name='Posizione (Indirizzo)')),
                ('posizione_lat', models.DecimalField(blank=True, decimal_places=6, help_text='Coordinate geografiche (opzionale)', max_digits=9, null=True, verbose_name='Latitudine')),
                ('posizione_lon', models.DecimalField(blank=True, decimal_places=6, help_text='Coordinate geografiche (opzionale)', max_digits=9, null=True, verbose_name='Longitudine')),
                ('dimensioni', models.CharField(blank=True, help_text='Es. 6x3m, 100x140cm', max_length=50, null=True, verbose_name='Dimensioni')),
                ('tipologia', models.CharField(choices=[('cartellone', 'Cartellone Stradale'), ('pensilina', 'Pensilina Autobus'), ('transenna', 'Transenna Parapedonale'), ('altro', 'Altro')], default='cartellone', max_length=50, verbose_name='Tipologia')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Altre Caratteristiche Rilevanti')),
                ('attivo', models.BooleanField(default=True, help_text='Indica se lo spazio è attualmente utilizzabile', verbose_name='Attivo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spazio Pubblicitario',
                'verbose_name_plural': 'Spazi Pubblicitari',
                'ordering': ['identificativo'],
            },
        ),
    ]
