# Generated by Django 5.2 on 2025-04-07 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0002_affissione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affissione',
            name='utente_creazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affissioni_create', to=settings.AUTH_USER_MODEL, verbose_name='Utente Creazione/Blocco'),
        ),
    ]
