# Generated by Django 5.2 on 2025-04-07 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0003_affissione_utente_creazione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInstallazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato_task', models.CharField(choices=[('DA_ASSEGNARE', 'Da Assegnare'), ('ASSEGNATO', 'Assegnato'), ('COMPLETATO', 'Completato'), ('PROBLEMA', 'Problema Segnalato')], default='DA_ASSEGNARE', max_length=20, verbose_name='Stato Task')),
                ('data_prevista_installazione', models.DateField(help_text="Normalmente coincide con la data inizio dell'affissione", verbose_name='Data Prevista Installazione')),
                ('note_admin', models.TextField(blank=True, null=True, verbose_name="Note per l'Installatore (da Admin)")),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('affissione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_installazione', to='gestione.affissione', verbose_name='Affissione Correlata')),
                ('installatore_assegnato', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Installatori'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assegnati', to=settings.AUTH_USER_MODEL, verbose_name='Installatore Assegnato')),
            ],
            options={
                'verbose_name': 'Task Installazione',
                'verbose_name_plural': 'Task Installazione',
                'ordering': ['data_prevista_installazione', 'stato_task'],
            },
        ),
    ]
